### ISSUE TITLE
Environment set up?

### ISSUE THREAD

**Issue by kulemandev** [JingleH/eSIM-OTA-SMDP#1]
I appreiciate This is project. Not many  SM-DP+ projet out there.

can you precise the environment in which you developped it espacially the web server.

Thank you!

**Comment by JingleH** [comment]
Hi there, I think it's a small flask server and I developed it on windows. Please note that this was just a quick and simple toy project so it's probably not very useful and many of the dependencies must be outdated or out of support. I'll recommend you look for other projects for inspirations. Feel free to download the code and I'll set this repo to private later

**Comment by kulemandev** [comment]
Thank you for clarifying.
Would you know any SM-DP+ project or software i can use. This is part of a
testbed project in my internship. Getting a alternative will really help.

Thank you for your time.
Regards

Le jeu. 15 sept. 2022 à 20:29, Jingle Huang ***@***.***> a
écrit :
